// Generates markdown content:
// -------------------------------------
// # {{org}}/{{repo}} documentation
//
// Docs:
// {{fileList}}
//
// This file was generated by vuepress-doc-reducer.js
//
const readmeFromTemplate = (org, repo, fileNames) => {
  // Get each file name as a link in a list item in md syntax
  const fileList = fileNames.map(
    (fileName) => `- [${fileName}](./${org}/${repo}/${fileName})\n`
  ).join("");

  return `
    # ${org}/${repo} documentation \n\n
    Docs: \n
    ${fileList}\n\n
    This file was generated by doc-reducer.js
  `;
};

module.exports = readmeFromTemplate;
