// Generates markdown content:
// -------------------------------------
// # {{org}}/{{repo}} documentation
//
// Docs:
// {{fileLinks}}
//
// This file was generated by vuepress-doc-reducer.js
//
const { html } = require('common-tags');

const readmeFromTemplate = (org, repo, files) => {
  // Get each file name as a link in a list item in md syntax
  const fileLinks = files.map(({ name }) => {
    return `- [${name}](./${org}/${repo}/${name})\n`;
  }).join('');

  return html`
    # ${org}/${repo} documentation \n\n
    Docs: \n
    ${fileLinks}\n\n
  `;
};

module.exports = readmeFromTemplate;
